load File.expand_path('../auth/oauth_gems.rb', __FILE__)
load File.expand_path('../auth/weibo_authenticator.rb', __FILE__)
load File.expand_path('../auth/renren_authenticator.rb', __FILE__)
load File.expand_path('../auth/douban_authenticator.rb', __FILE__)
load File.expand_path('../auth/qq_authenticator.rb', __FILE__)
load File.expand_path('../auth/wechat_authenticator.rb', __FILE__)
